steps:
- name: 'bash'
  script: |
    #!/usr/bin/env bash
    echo "Testing GCP Cloud Build"
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull saurabhthatte/foss-scan:aws']
